CREATE TABLE categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        icon VARCHAR(100),
        type VARCHAR(20) NOT NULL,
        user_id BIGINT,
        created_at TIMESTAMP NOT NULL,
        updated_at TIMESTAMP NOT NULL,

        CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users(id),
        CONSTRAINT chk_categories_type CHECK (type IN ('DEFAULT', 'CUSTOM')),
        CONSTRAINT chk_categories_owner CHECK (
            (type = 'DEFAULT' AND user_id IS NULL)
                OR
            (type = 'CUSTOM' AND user_id IS NOT NULL))
);

CREATE INDEX idx_categories_user_type ON categories(user_id, type);

CREATE UNIQUE INDEX uk_categories_default_name ON categories(LOWER(TRIM(name))) WHERE type = 'DEFAULT';

CREATE UNIQUE INDEX uk_categories_custom_user_name ON categories(user_id, LOWER(TRIM(name))) WHERE type = 'CUSTOM';