INSERT INTO categories (name, type, created_at, updated_at)
VALUES
    ('Alimentação', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Carnes e Peixes', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bebidas', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Frutas e Vegetais', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Laticínios', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Higiene Pessoal', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Limpeza', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bebé / Crianças', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Outros', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);